### ISSUE TITLE
登录跳转login.html，但并没有这个文件

### ISSUE THREAD

**Issue by dingyadong** [CHANGEX929/RCMS#3]
我打开login.jsp文件登录后自动跳转login.html，但并没有这个文件，我不知道是在哪个步骤上错了？请你指点一下。

**Comment by hiTiffeny** [comment]
请问您这个问题是怎么解决的啊

**Comment by hiTiffeny** [comment]
> 我打开login.jsp文件登录后自动跳转login.html，但并没有这个文件，我不知道是在哪个步骤上错了？请你指点一下。

请问您是怎么解决这个问题的啊？
