### ISSUE TITLE
添加菜品后图片不显示

### ISSUE THREAD

**Issue by MrJackC** [CHANGEX929/RCMS#5]
您好：
在本地部署了您的项目后，运行后发现，新增的菜品，菜品中的图片不显示，方便帮忙解决一下吗？
谢谢~~

**Comment by CHANGEX929** [comment]
新增菜品，图片名不能为中文。

**Comment by MrJackC** [comment]
不好意思  没能 技术回复您   在提出问题之后，我看了一下代码和报错的信息，就解决的错误，但是依然感谢您能回复。谢谢
